---
substitutions:
  device_name: "slimmelezer"
  device_friendly_name: "SlimmeLezer"
  device_description: "Okosmérő P1 port kiolvasó"
esphome:
  name: ${device_name}
  comment: "${device_description}"
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"
esp8266:
  board: d1_mini
  restore_from_flash: true

external_components:
  - source: github://amargo/slimmelezer-eon[@main]
    components: [dsmr]

wifi:
  ap:
    ssid: ${device_name}

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: INFO
  # logs:
  #   api: INFO
  #   api.service: INFO
  #   sensor: DEBUG
  #   text_sensor: DEBUG
  #   esphome: INFO
  #   ota: INFO
  #   wifi: INFO
  #   captive_portal: INFO
  #   web_server: INFO
  #   uart: INFO
  #   scheduler: INFO

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3000

dsmr:
  id: dsmr_instance
  crc_check: false
  max_telegram_length: 3000

sensor:
  - platform: dsmr
    energy_delivered:
      name: "Hatásos vételezett energia (+A)"
      accuracy_decimals: 3
    energy_delivered_tariff1:
      name: "Hatásos vételezett energia (+A) tarifa 1"
      accuracy_decimals: 3
    energy_delivered_tariff2:
      name: "Hatásos vételezett energia (+A) tarifa 2"
      accuracy_decimals: 3
    # 3-4 egyelőre inaktív (2023.03.27)
    energy_delivered_tariff3:
      name: "Hatásos vételezett energia (+A) tarifa 3"
      accuracy_decimals: 3
    energy_delivered_tariff4:
      name: "Hatásos vételezett energia (+A) tarifa 4"
      accuracy_decimals: 3

    power_delivered_l1:
      name: "Pillanatnyi teljesítmény L1 - hatásos vételezett (+A)"
      accuracy_decimals: 3
      id: power_delivered_l1
      internal: true
      on_value:
        - script.execute: update_phase_power
    power_delivered_l2:
      name: "Pillanatnyi teljesítmény L2 - hatásos vételezett (+A)"
      accuracy_decimals: 3
      id: power_delivered_l2
      internal: true
      on_value:
        - script.execute: update_phase_power
    power_delivered_l3:
      name: "Pillanatnyi teljesítmény L3 - hatásos vételezett (+A)"
      accuracy_decimals: 3
      id: power_delivered_l3
      internal: true
      on_value:
        - script.execute: update_phase_power

    power_returned_l1:
      name: "Pillanatnyi teljesítmény L1 - hatásos betáplált (-A)"
      accuracy_decimals: 3
      id: power_returned_l1
      internal: true
      on_value:
        - script.execute: update_phase_power
    power_returned_l2:
      name: "Pillanatnyi teljesítmény L2 - hatásos betáplált (-A)"
      accuracy_decimals: 3
      id: power_returned_l2
      internal: true
      on_value:
        - script.execute: update_phase_power
    power_returned_l3:
      name: "Pillanatnyi teljesítmény L3 - hatásos betáplált (-A)"
      accuracy_decimals: 3
      id: power_returned_l3
      internal: true
      on_value:
        - script.execute: update_phase_power

    power_delivered:
      name: "Pillanatnyi teljesítmény - hatásos vételezett (+A)"
      accuracy_decimals: 3
      id: power_consumed
      on_value:
        - script.execute: update_power_balance
    power_returned:
      name: "Pillanatnyi teljesítmény - hatásos betáplált (-A)"
      accuracy_decimals: 3
      id: power_produced
      on_value:
        - script.execute: update_power_balance

    energy_returned:
      name: "Hatásos betáplált energia (-A)"
      accuracy_decimals: 3
    energy_returned_tariff1:
      name: "Hatásos betáplált energia (-A) tarifa 1"
      accuracy_decimals: 3
    energy_returned_tariff2:
      name: "Hatásos betáplált energia (-A) tarifa 2"
      accuracy_decimals: 3
    # 3-4 egyelőre inaktív (2023.03.27)
    energy_returned_tariff3:
      name: "Hatásos betáplált energia (-A) tarifa 3"
      accuracy_decimals: 3
    energy_returned_tariff4:
      name: "Hatásos betáplált energia (-A) tarifa 4"
      accuracy_decimals: 3

    electricity_tariff:
      name: "Aktuális tarifa"
    # Frekvencia 2024-től kikerült
    #frequency:
    #  name: "Frekvencia"
    #  accuracy_decimals: 2
    energy_absolute:
      name: "Összes hatásos energia - vételezett és betáplált"

    voltage_l1:
      name: "Fázisfeszültség L1"
      id: voltage_l1
      on_value:
        - script.execute: update_phase_power
    voltage_l2:
      name: "Fázisfeszültség L2"
      id: voltage_l2
      on_value:
        - script.execute: update_phase_power
    voltage_l3:
      name: "Fázisfeszültség L3"
      id: voltage_l3
      on_value:
        - script.execute: update_phase_power
    current_l1:
      name: "Pillanatnyi áramerősség L1"
      accuracy_decimals: 1
      id: current_l1
    current_l2:
      name: "Pillanatnyi áramerősség L2"
      accuracy_decimals: 1
      id: current_l2
    current_l3:
      name: "Pillanatnyi áramerősség L3"
      accuracy_decimals: 1
      id: current_l3

    instantaneous_power_factor:
      name: "Teljesítménytényező - eredő"
      device_class: power_factor
      accuracy_decimals: 1
    instantaneous_power_factor_l1:
      name: "Teljesítménytényező L1"
      device_class: power_factor
      accuracy_decimals: 1
      id: instantaneous_power_factor_l1
    instantaneous_power_factor_l2:
      name: "Teljesítménytényező L2"
      device_class: power_factor
      accuracy_decimals: 1
      id: instantaneous_power_factor_l2
    instantaneous_power_factor_l3:
      name: "Teljesítménytényező L3"
      device_class: power_factor
      accuracy_decimals: 1
      id: instantaneous_power_factor_l3

    reactive_power_qi:
      name: "Pillanatnyi teljesítmény - meddő (QI)"
      device_class: reactive_power
      accuracy_decimals: 3
    reactive_power_qii:
      name: "Pillanatnyi teljesítmény - meddő (QII)"
      device_class: reactive_power
      accuracy_decimals: 3
    reactive_power_qiii:
      name: "Pillanatnyi teljesítmény - meddő (QIII)"
      device_class: reactive_power
      accuracy_decimals: 3
    reactive_power_qiv:
      name: "Pillanatnyi teljesítmény - meddő (QIV)"
      device_class: reactive_power
      accuracy_decimals: 3

    energy_positive_reactive:
      name: "Meddő energia - vételezett (+R)"
      id: energy_positive_reactive
    energy_negative_reactive:
      name: "Meddő energia - betáplált (-R)"
      id: energy_negative_reactive
    reactive_energy_qi:
      name: "Meddő energia (QI)"
    reactive_energy_qii:
      name: "Meddő energia (QII)"
    reactive_energy_qiii:
      name: "Meddő energia (QIII)"
    reactive_energy_qiv:
      name: "Meddő energia (QIV)"
    # Mérőóra áramkorlátozó felügyeletének beállítási értéke
    electricity_threshold_l1:
      name: "Áramkorlátozó felügyelet küszöbértéke L1"
    electricity_threshold_l2:
      name: "Áramkorlátozó felügyelet küszöbértéke L2"
    electricity_threshold_l3:
      name: "Áramkorlátozó felügyelet küszöbértéke L3"

    electricity_threshold:
      name: "Áramkorlátozó küszöbértéke"

  - platform: uptime
    name: "SlimmeLezer üzemidő"
    device_class: duration
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi jel"
    update_interval: 60s

  - platform: template
    name: "Pillanatnyi teljesítmény - hatásos eredő"
    id: power_balance
    unit_of_measurement: kW
    state_class: measurement
    device_class: power
    accuracy_decimals: 3

  # Net power per phase (positive = consumption, negative = production)
  - platform: template
    name: "Pillanatnyi teljesítmény L1 - nettó"
    id: power_net_l1
    unit_of_measurement: kW
    device_class: power
    state_class: measurement
    accuracy_decimals: 3
    update_interval: never

  - platform: template
    name: "Pillanatnyi teljesítmény L2 - nettó"
    id: power_net_l2
    unit_of_measurement: kW
    device_class: power
    state_class: measurement
    accuracy_decimals: 3
    update_interval: never

  - platform: template
    name: "Pillanatnyi teljesítmény L3 - nettó"
    id: power_net_l3
    unit_of_measurement: kW
    device_class: power
    state_class: measurement
    accuracy_decimals: 3
    update_interval: never

  # Net current per phase (I = P_net[kW]*1000 / U[V])
  - platform: template
    name: "Pillanatnyi áramerősség L1 - nettó"
    id: current_net_l1
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    name: "Pillanatnyi áramerősség L2 - nettó"
    id: current_net_l2
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    name: "Pillanatnyi áramerősség L3 - nettó"
    id: current_net_l3
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    update_interval: never

  # Net reactive energy (positive = consumed, negative = produced)
  - platform: template
    name: "Meddő energia - nettó"
    id: reactive_energy_net
    unit_of_measurement: kvarh
    state_class: measurement
    accuracy_decimals: 3
    lambda: |-
      float positive = id(energy_positive_reactive).state;
      float negative = id(energy_negative_reactive).state;
      return positive - negative;

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP"
      update_interval: 60s
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
      update_interval: 60s
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID"
      update_interval: 60s

  - platform: dsmr
    #identification:
    #  name: "COSEM logikai készüléknév"
    #equipment_id:
    #  name: "Mérő gyáriszám"

    #Mérőtől függő konfig (valamelyik működik)
    breaker_status:
      name: "Megszakító státusz"
    breaker_status_b:
      name: "Megszakító státusz B"

  - platform: version
    name: "ESPHome verzió és build"
    hide_timestamp: false

script:
  - id: update_power_balance
    mode: single
    then:
      - lambda: |-
          id(power_balance).publish_state(id(power_produced).state-id(power_consumed).state);
  - id: update_phase_power
    mode: queued
    then:
      - lambda: |-
          auto r3 = [](float v){ return roundf(v * 1000.0f) / 1000.0f; };
          auto r2 = [](float v){ return roundf(v * 100.0f) / 100.0f; };
          // Read base values
          float pd1 = id(power_delivered_l1).state; float pr1 = id(power_returned_l1).state;
          float pd2 = id(power_delivered_l2).state; float pr2 = id(power_returned_l2).state;
          float pd3 = id(power_delivered_l3).state; float pr3 = id(power_returned_l3).state;
          float u1 = id(voltage_l1).state; float u2 = id(voltage_l2).state; float u3 = id(voltage_l3).state;
          float i1m = id(current_l1).state; float i2m = id(current_l2).state; float i3m = id(current_l3).state;
          float pf1 = id(instantaneous_power_factor_l1).state; float pf2 = id(instantaneous_power_factor_l2).state; float pf3 = id(instantaneous_power_factor_l3).state;
          // Compute net power per phase. Primary source: delivered-returned. Fallback: U*I*PF/1000.
          auto fallback_p = [](float u, float i, float pf){
            if (isnan(u) || u <= 1.0f || isnan(i) || i < 0.0f) return NAN;
            if (isnan(pf) || pf <= 0.0f) pf = 1.0f;
            return (u * i * pf) / 1000.0f;
          };
          float n1 = (!isnan(pd1) && !isnan(pr1)) ? (pd1 - pr1) : fallback_p(u1, i1m, pf1);
          float n2 = (!isnan(pd2) && !isnan(pr2)) ? (pd2 - pr2) : fallback_p(u2, i2m, pf2);
          float n3 = (!isnan(pd3) && !isnan(pr3)) ? (pd3 - pr3) : fallback_p(u3, i3m, pf3);
          id(power_net_l1).publish_state(r3(n1));
          id(power_net_l2).publish_state(r3(n2));
          id(power_net_l3).publish_state(r3(n3));
          // Compute net current per phase from power/voltage; fallback to meter current
          auto current_from_pu = [](float p_kw, float u){
            if (!isnan(p_kw) && u > 1.0f) return p_kw * 1000.0f / u; else return NAN;
          };
          float in1 = current_from_pu(n1, u1); if (isnan(in1)) in1 = i1m;
          float in2 = current_from_pu(n2, u2); if (isnan(in2)) in2 = i2m;
          float in3 = current_from_pu(n3, u3); if (isnan(in3)) in3 = i3m;
          id(current_net_l1).publish_state(r2(in1));
          id(current_net_l2).publish_state(r2(in2));
          id(current_net_l3).publish_state(r2(in3));
